### ISSUE TITLE
Setup IBM Cloud and invite the team

### ISSUE THREAD

**Issue by sahilbakshi98** [CSCI-GA-2820-SU23-001/products#29]
**As a** developer
**I need** to deploy the service on IBM Cloud and add all team members to the group
**So that** every developer can use the cloud's shared resources instead of being hindered by the limitations of one's local system.
   
 ### Details and Assumptions
 * Every developer on the team has an IBM Cloud account
   
 ### Acceptance Criteria  
   
 ```gherkin
Every team member can access the products service on IBM Cloud.
```

**Comment by Leslielu7** [comment]
Should we also include "inviting the team on IBM cloud" in this story?

**Comment by sahilbakshi98** [comment]
@Leslielu7 Yep, I'll edit it accordingly. Thanks!
