### ISSUE TITLE
Develop a RESTful API to Update a Product 

### ISSUE THREAD

**Issue by Alan-Ou** [CSCI-GA-2820-SU23-001/products#5]
**As a** user
**I need** a way to update the information of product   
**So that** I could do some modification for each product   
   
 ### Details and Assumptions
 * The url for this specific task should be /products/{product_id}
 * The type of method should be PUT
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that I have modified the price information of product A to 100
 When I make a call to get the current price for product A
 Then it should return 100
```

**Comment by Leslielu7** [comment]
Should we also add a "enhancement" blue label (in the "Labels" function) to this issue like other developing REST API issues ?

**Comment by sahilbakshi98** [comment]
Alan had mentioned that he is having trouble with adding the label. Prof had given a fix for a similar issue to another team. Let’s wait and see if he can resolve the issue.

**Comment by sahilbakshi98** [comment]
Will we need to have separate categories for customers and merchants for the update product functionality? A customer should not be able to edit the price of a product, whereas a merchant should, right?

**Comment by Leslielu7** [comment]
> Will we need to have separate categories for customers and merchants for the update product functionality? A customer should not be able to edit the price of a product, whereas a merchant should, right?

Make sense. Does it also apply to "Delete" a Product?

**Comment by sahilbakshi98** [comment]
> > Will we need to have separate categories for customers and merchants for the update product functionality? A customer should not be able to edit the price of a product, whereas a merchant should, right?
> 
> Make sense. Does it also apply to "Delete" a Product?

Yep we'll have to consider that one as well
