### ISSUE TITLE
Develop a REST API to list products

### ISSUE THREAD

**Issue by Xin123456Zx** [CSCI-GA-2820-SU23-001/products#7]

**Comment by Xin123456Zx** [comment]
**As a** user
**I need** a way to list products 
**So that**  I can browse and select from all available products
   
 ### Details and Assumptions
 * The base URL would be /products/{product_id}
 * The server infrastructure is set up and available
 *  The database containing product data is set up and available
 ### Acceptance Criteria  
   
 ```gherkin
 Given the server is available
 When I call the URL 'GET/products'
 The database containing product data is set up and available
 Then I should be able to list all the product or return an error code.
```

**Comment by Leslielu7** [comment]
Should we add this to next Sprint (starting from Jun 22) along with other stories about building REST API?
